DROP TABLE locations CASCADE CONSTRAINTS;

CREATE TABLE locations (
    location_id     VARCHAR2(5) PRIMARY KEY,
    location_name   VARCHAR2(20)
);

DROP TABLE customers CASCADE CONSTRAINTS;

CREATE TABLE customers (
    cust_id     VARCHAR2(5) PRIMARY KEY,
    cust_name   VARCHAR2(50) NOT NULL,
    phone       VARCHAR2(15) NOT NULL UNIQUE,
    email       VARCHAR2(30) NOT NULL UNIQUE,
    address     VARCHAR2(100),
    loc_id      VARCHAR2(5)
        REFERENCES locations ( location_id )
);

DROP TABLE products CASCADE CONSTRAINTS;

CREATE TABLE products (
    product_id      VARCHAR2(5) PRIMARY KEY,
    product_name    VARCHAR2(50) NOT NULL,
    product_desc    VARCHAR2(100),
    product_price   NUMBER NOT NULL,
    product_stock   NUMBER NOT NULL
);

DROP TABLE order_status_desc CASCADE CONSTRAINTS;

CREATE TABLE order_status_desc (
    status        VARCHAR2(10) PRIMARY KEY,
    status_desc   VARCHAR2(50)
);

DROP TABLE orders CASCADE CONSTRAINTS;

CREATE TABLE orders (
    order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cust_id       VARCHAR2(5) NOT NULL
        REFERENCES customers ( cust_id ),
    product_id    VARCHAR2(5) NOT NULL
        REFERENCES products ( product_id ),
    order_date    DATE DEFAULT SYSDATE,
    product_qty   NUMBER,
    price         NUMBER,
    status        VARCHAR2(10)
        REFERENCES order_status_desc ( status )
);

DROP TABLE invoices CASCADE CONSTRAINTS;

CREATE TABLE invoices (
    invoice_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id       NUMBER
        REFERENCES orders ( order_id ),
    total_amount   NUMBER,
    sgst           NUMBER,
    cgst           NUMBER
);


/